### ISSUE TITLE
[Bug] Browser client is out of date, please refresh the page header was 7.14.1 but should be 7.14.0

### ISSUE THREAD

**Issue by koelslaw** [thremulation-station/thremulation-station#102]
**Describe the bug**
Differing version of elastic stack between packer built vagrant boxes and the configuration of the fleet server. 7.14.0 vs 7.14.1. 

**To Reproduce**
1. deploy 0.9.3-dev branch 

**Expected behavior**
not fail

**Screenshots**
https://github.com/thremulation-station/thremulation-station/runs/3599245614?check_suite_focus=true#step:3:281

**Additional context**

Need to pin this to a specific version:

https://github.com/thremulation-station/thremulation-station/blob/ff6cd1a96b7ef3a5e6d9f53b2f303bf7049e1ad8/packer/vbox-elastic/ansible/elastic-playbook.yml#L208

**Comment by koelslaw** [comment]
Which version are we pin too? @seven62 @DefSecSentinel @webhead404 ?

**Comment by seven62** [comment]
This issue can be tested once new test boxes are built on new infra.

**Comment by webhead404** [comment]
#116 fixes this issue by pinning both Elasticsearch and Kibana to 7.14.0. Recommend we bump to 7.14.2 when we feel like we are in a good spot.
