### ISSUE TITLE
Add a step to Windows vagrant up that clears all the logs so alerts don't fire in the SIEM on all the provisioning steps.

### ISSUE THREAD

**Issue by webhead404** [thremulation-station/thremulation-station#104]
Makes sense to add this elsewhere so I dropped it in CentOS instead. It seems like it take a long time for all the alerts to populate during vagrant up. We could have CentOS script wait around 5 minutes before executing the delete or move some functions around. Will warrant a little discussion!

**Comment by webhead404** [comment]
#105 should fix this once we get the chance to discuss next steps.

**Comment by seven62** [comment]
Resolved with merging of PR #105
