### ISSUE TITLE
[Bug] Stationctl "start" reprovisions

### ISSUE THREAD

**Issue by peasead** [thremulation-station/thremulation-station#28]
**Describe the bug**
When running `stationctl` and Startup, it reprovisions the boxes.

**To Reproduce**
1. `stationctl`
2. `4`
3. `2`

**Expected behavior**
Just restart the boxes without reprovisioning them.

This can be fixed by changing `stationctl` to start (and restart boxes) with `vagrant {up,reload} --no-provision

**Comment by seven62** [comment]
This is already added to file. May in fact be causing #47

**Comment by seven62** [comment]
Closing, as this issue is being addressed in #49
