### ISSUE TITLE
[Bug] Vagrant disksize plugin doesn't resize root filesystem

### ISSUE THREAD

**Issue by dcode** [thremulation-station/thremulation-station#43]
**Describe the bug**
We're using the vagrant plugin `disksize` to increase the disk storage, but within the VM, the actual filesystem remains the same

**To Reproduce**
1. Launch the `ts.elastomic` VM per the instructions
2. SSH into the system
3. Run `lsblk`
4. See root partition is only 50G
```
NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda               8:0    0  256G  0 disk
├─sda1            8:1    0    1G  0 part /boot
└─sda2            8:2    0   79G  0 part
  ├─centos-root 253:0    0   50G  0 lvm  /
  ├─centos-swap 253:1    0  3.9G  0 lvm  [SWAP]
  └─centos-home 253:2    0 25.1G  0 lvm  /home
```

**Expected behavior**
I expected the filesystem to have grown to the configured value in the `Vagrantfile` like so:

```
NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda               8:0    0  256G  0 disk
├─sda1            8:1    0    1G  0 part /boot
└─sda2            8:2    0  255G  0 part
  ├─centos-root 253:0    0  226G  0 lvm  /
  ├─centos-swap 253:1    0  3.9G  0 lvm  [SWAP]
  └─centos-home 253:2    0 25.1G  0 lvm  /home
```

**Proposed fix**

The following script could be used as a systemd service on boot to grow this. Fortunately, XFS can be resized while online, but that should probably happen before you launch Elasticsearch or other services.

```bash
#!/bin/bash

the_root_device='/dev/sda'
the_dynamic_partition='2'
the_dynamic_partition_path="${the_root_device}${the_dynamic_partition}"
the_root_vgname='centos'
the_root_lvname='root'
the_root_lvpath="/dev/${the_root_vgname}/${the_root_lvname}"

# Grow the partition table
growpart "${the_root_device}" "${the_dynamic_partition}"
sync; sync; sync

# Reload the partition table
partprobe
sync; sync; sync

# Resize the physical volume group
pvresize "${the_dynamic_partition_path}"
sync; sync; sync

# Resize logical volume to the full disk, then grow the filesystem
lvresize -l +100%FREE --resizefs /dev/centos/root
sync; sync; sync
````

The above depends on the following

```
sudo yum install cloud-utils-growpart
```

**Better fix**

To further simplify your life, update the Elastomic box using standard partitions instead of LVM, then all you have to do is install the following and reboot. The root partition will auto-resize any time there is free space when booted.

```
sudo yum install cloud-utils-growpart cloud-init
```

**Comment by koelslaw** [comment]
Included `sudo yum install -y cloud-utils-growpart` into the above bash script and added it to the vagrant file just before elastic provisioning. initial tests look good. rebuilding a clean env and testing changes again. 

Branch: https://github.com/thremulation-station/thremulation-station/tree/kirk-vagrant-disksize

**Comment by koelslaw** [comment]
Build is Good 

![image](https://user-images.githubusercontent.com/29241476/132103705-c3e12095-ff5b-4214-8510-0e5f370b05c7.png)

**Comment by DefSecSentinel** [comment]
Fixed by Kirk.
