### ISSUE TITLE
[Bug] - ts.elastomic parse error. Invalid numeric liternal at line 1, column 7.

### ISSUE THREAD

**Issue by webhead404** [thremulation-station/thremulation-station#69]
**Describe the bug**
`ts.elastomic` appears to hit a bug during the build process. Right after `oniguruma.x86_64 0:6.8.2-1.el7` is installed. Before that `jq` is installed and after some troubleshooting it seems like it has troubles parsing the output for the elastic checks. I have nuked the whole environment and this still appears to be happening. 

**To Reproduce**
1. Start `./stationctl` with normal deployment options. 

**Expected behavior**
`ts.elastomic` builds successfully and moves on to build ts.windows10 and so on.

**Screenshots**

![parse error](https://user-images.githubusercontent.com/8658818/113318970-9b3c2980-92d6-11eb-9422-a6347aa36328.PNG)

**Additional context and troubleshooting**
Running latest build of Vagrant (2.2.15) and VirtualBox (6.1.18) on Windows 10.

**Comment by seven62** [comment]
@webhead404 thanks for filing this issue! I'll be working on testing builds on updated packages soon and report back

**Comment by webhead404** [comment]
Awesome, thanks @seven62 !

**Comment by webhead404** [comment]
This issue is because sometimes Kibana isn't ready for requests. This should be fixed in the future with the fleet installer script
