### ISSUE TITLE
[Documentation] Open Source?

### ISSUE THREAD

**Issue by weslambert** [thremulation-station/thremulation-station#88]
Great work on this! Really appreciate what's been done here.  

However, I was wondering...the project states it's a collection of `open source` tools, but given the recent changes with Elastic licensing (RE: https://www.elastic.co/pricing/faq/licensing#does-this-mean-that-elasticsearch-and-kibana-are-no-longer-open-source), I'd suggest changing the wording in the README to refer to `free and open` tools to avoid confusion and misrepresentation of licensing.

**Comment by koelslaw** [comment]
Thank you for the feedback on the documentation. We will take a look and discuss.
