### ISSUE TITLE
Centos Endpoint Agent shows as not healthy and quits sending logs.

### ISSUE THREAD

**Issue by DefSecSentinel** [thremulation-station/thremulation-station#92]
I believe this may be due to too much happening on the host to include filebeat, auditbeat and the agent all working at once. I think there is some overlap there so we need to asses what the endpoint is picking up vs filebeat and auditbeat. If the endpoint picks up all or most of those logs we can get rid of filebeat and auditbeat but this needs to be tested.

On Centos7:

- [ ] remove Auditbeat
- [x] remove Journalbeat
- [ ] Filebeat additional logs
    - [ ] Nginx logs
    - [ ] Samba logs

**Comment by seven62** [comment]
Need help to duplicating issue.

**Comment by DefSecSentinel** [comment]
Investigated and found that we can get rid of Audibeat, Filebeat, and Journalbeat but we do need to figure out how to add a log pick up path to the system integration to grab the Nginx and Samba logs.

**Comment by seven62** [comment]
Remove Auditbeat and Journalbeat but leave Filebeat to pick up Nginx and Samba logs

**Comment by seven62** [comment]
Building new box for testing.

**Comment by seven62** [comment]
- auditbeat task and file can be removed.
- existing journalbeat config isn't being used

**Comment by seven62** [comment]
Followup tasks:

- leave the "Copy Auditd Configuration" task
- remove the 
  - "Stop. Auditd Service"
  - "Disable Auditd Service"
